name: Applitools - Run Ultrafast Grid v2

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use java ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Install dependencies
        run: mvn install

      - name: RunTest
        run: mvn exec:java -Dexec.mainClass="com.applitools.quickstarts.AppTest"  -Dexec.classpathScope=test
        env:
          APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
          BASEURL: https://demo.applitools.com/index_v2.html
          USE_GRID: true
